# Generated by Django 5.1 on 2025-01-17 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('genre', models.IntegerField()),
                ('origin', models.CharField(max_length=100)),
                ('skin', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterStats',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CharacterWeapon',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Enchantment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EnchantmentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('maxLevel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserCharacter',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('maxLevel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='MainModel',
        ),
        migrations.AddField(
            model_name='enchantment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.enchantmenttype'),
        ),
        migrations.AddField(
            model_name='character',
            name='lastLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.location'),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.race'),
        ),
        migrations.AddField(
            model_name='characterstats',
            name='stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stats'),
        ),
        migrations.AddField(
            model_name='usercharacter',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.character'),
        ),
        migrations.AddField(
            model_name='usercharacter',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='characterweapon',
            name='userCharacter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usercharacter'),
        ),
        migrations.AddField(
            model_name='characterstats',
            name='UserCharacter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usercharacter'),
        ),
        migrations.AddField(
            model_name='characterweapon',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.weapon'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.weapontype'),
        ),
    ]
