# Generated by Django 5.1.1 on 2025-03-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_chatmessage_id_alter_chatprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatprofile',
            name='jsonText',
            field=models.TextField(null=True),
        ),
    ]
